### PR TITLE
fix: set DHCP Option 6 (DNS Server) in OpenWrt install

### LINKED ISSUE #870: add force dns server in openwrt
**Context**

I'm running nextdns on openwrt on x86

here is myconfig
```
# nextdns config
listen localhost:53
profile xxxxx
cache-max-age 0s
discovery-dns
detect-captive-portals false
timeout 5s
log-queries false
cache-size 100MB
mdns all
bogus-priv true
use-hosts true
debug false
control /var/run/nextdns.sock
max-ttl 0s
report-client-info true
hardened-privacy false
max-inflight-requests 256
setup-router true
auto-activate false

```

All works well, but DHCP( Bootp) wasn't giving out DNS server via BOOTP (option 6)

I had to force it from LUCI.. network >> interfaces >> edit br-lan >> DHCP Server >> Advanced >> DHCP-Options

and add
`6,192.168.50.1` (50.1 is my router's IP)

image

This will add a config entry in `/etc/config/dhcp` under  `config dhcp 'lan'` 
```
config dhcp 'lan'
        option interface 'lan'
        option start '100'
        option limit '150'
        option leasetime '12h'
        option dhcpv4 'server'
        option force '1'
        list dhcp_option '6,192.168.50.1'

```

can we make the https://github.com/nextdns/nextdns/blob/7da8f4c0657f1f23f16fa8258fd8108bf8ee8a76/router/openwrt/setup.go#L52 to automatically add this line?

### PR DESCRIPTION
**Pull request by rriski**
Fixes #870.

The lack of explicit DHCP Option 6 on `lan` interface broke client DNS resolution on (at least) recent MacOS clients after `nextdns install`. This commit fixes the issue by setting option 6 in `dhcp.lan.dhcp_option` explicitly.

### CODE REVIEW

File: router/openwrt/setup.go [hunk 1]
```diff
@@ -122,6 +155,14 @@ func (r *Router) Restore() error {
 	// Remove the custom dnsmasq config
 	_ = os.Remove(r.DNSMasqPath)
 
+	// Remove the DHCP option 6 (DNS server) if it was set
+	if _, err := uci("del", "dhcp.lan.dhcp_option"); err != nil {
```
Comment (rs) [inline router/openwrt/setup.go:159]: Is there a chance this option was available before? Could removing it leave the router misconfigured?

Comment (rriski) [reply router/openwrt/setup.go:159]: Good point, we can use `uci del_list dhcp.lan.dhcp_option="6,router_ip_here"` to only remove the added configuration. I have updated the PR. `del_list` doesn't throw an error when `dhcp_option` is empty or if the specified option is not included in the current configuration.
